[2024-06-28T17:54:00.877+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:54:00.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:53:50.340198+00:00 [queued]>
[2024-06-28T17:54:00.925+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:53:50.340198+00:00 [queued]>
[2024-06-28T17:54:00.925+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:54:00.944+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:53:50.340198+00:00
[2024-06-28T17:54:00.954+0000] {standard_task_runner.py:63} INFO - Started process 167 to run task
[2024-06-28T17:54:00.958+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:53:50.340198+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmp1t7kqd6i']
[2024-06-28T17:54:00.961+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask data_delivery
[2024-06-28T17:54:01.028+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:53:50.340198+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:54:01.348+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:53:50.340198+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:53:50.340198+00:00'
[2024-06-28T17:54:01.349+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:54:01.367+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:54:01.367+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:54:01.377+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:54:01.382+0000] {Load_Data.py:89} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T17:54:01.384+0000] {Load_Data.py:143} INFO - Error loading location dimension: 'LocationID'
[2024-06-28T17:54:01.384+0000] {Load_Data.py:147} INFO - loading DimRate Dimension ...
[2024-06-28T17:54:01.387+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:54:01.391+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:54:01.398+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:54:01.398+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:54:01.399+0000] {Load_Data.py:150} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:54:01.399+0000] {Load_Data.py:165} INFO - loading payment dimension....
[2024-06-28T17:54:01.403+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:54:01.406+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:54:01.414+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:54:01.414+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:54:01.415+0000] {Load_Data.py:168} INFO - payment_df dimension loaded successfully
[2024-06-28T17:54:01.415+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:54:01.422+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:54:01.427+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:54:01.427+0000] {Load_Data.py:156} INFO - loading trip_type dimension....
[2024-06-28T17:54:01.429+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:54:01.433+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:54:01.438+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:54:01.439+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:54:01.439+0000] {Load_Data.py:159} INFO - trip_df dimension loaded successfully
[2024-06-28T17:54:01.439+0000] {Load_Data.py:174} INFO - loading fact table ....
[2024-06-28T17:54:05.305+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:54:05.308+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:55:06.555+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T17:55:06.556+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T17:55:06.558+0000] {process_utils.py:132} INFO - Sending 15 to group 167. PIDs of all processes in the group: [167]
[2024-06-28T17:55:06.558+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 167
[2024-06-28T17:55:06.558+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T17:55:06.564+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:55:06.771+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=167, status='terminated', exitcode=0, started='17:54:00') (167) terminated with exit code 0
