[2024-06-28T17:25:01.880+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T17:25:01.900+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:24:51.469182+00:00 [queued]>
[2024-06-28T17:25:01.909+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:24:51.469182+00:00 [queued]>
[2024-06-28T17:25:01.909+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T17:25:01.920+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 17:24:51.469182+00:00
[2024-06-28T17:25:01.927+0000] {standard_task_runner.py:63} INFO - Started process 104 to run task
[2024-06-28T17:25:01.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T17:24:51.469182+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpb2ufoz3z']
[2024-06-28T17:25:01.932+0000] {standard_task_runner.py:91} INFO - Job 44: Subtask data_delivery
[2024-06-28T17:25:01.971+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T17:24:51.469182+00:00 [running]> on host 79a59ce16f65
[2024-06-28T17:25:02.276+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T17:24:51.469182+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T17:24:51.469182+00:00'
[2024-06-28T17:25:02.277+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T17:25:02.289+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T17:25:02.289+0000] {Load_Data.py:73} INFO - Loading location Dimension ...
[2024-06-28T17:25:02.297+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:25:02.303+0000] {Load_Data.py:148} INFO - Error loading location dimension: 'start_date'
[2024-06-28T17:25:02.304+0000] {Load_Data.py:152} INFO - loading DimRate Dimension ...
[2024-06-28T17:25:02.307+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T17:25:02.310+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:25:02.316+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T17:25:02.316+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:25:02.316+0000] {Load_Data.py:155} INFO - DimRate_df dimension loaded successfully
[2024-06-28T17:25:02.317+0000] {Load_Data.py:170} INFO - loading payment dimension....
[2024-06-28T17:25:02.320+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T17:25:02.323+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:25:02.328+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T17:25:02.329+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:25:02.329+0000] {Load_Data.py:173} INFO - payment_df dimension loaded successfully
[2024-06-28T17:25:02.329+0000] {Load_Data.py:11} INFO - Loading vendor Dimension ...
[2024-06-28T17:25:02.334+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:25:02.338+0000] {Load_Data.py:69} INFO - Error loading vendor dimension: 'vendor_name'
[2024-06-28T17:25:02.338+0000] {Load_Data.py:161} INFO - loading trip_type dimension....
[2024-06-28T17:25:02.340+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T17:25:02.343+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:25:02.347+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T17:25:02.348+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:25:02.348+0000] {Load_Data.py:164} INFO - trip_df dimension loaded successfully
[2024-06-28T17:25:02.348+0000] {Load_Data.py:179} INFO - loading fact table ....
[2024-06-28T17:25:06.068+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T17:25:06.072+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T17:28:07.813+0000] {Table_creation.py:45} INFO - Data loaded successfully into table Fact_Trip With 618792 Row
[2024-06-28T17:28:07.814+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T17:28:13.052+0000] {Load_Data.py:201} INFO - Fact_df  loaded successfully
[2024-06-28T17:28:13.078+0000] {NYC_Taxi_pipeline.py:61} INFO - data_delivery done
[2024-06-28T17:28:13.079+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-28T17:28:13.079+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T17:28:13.088+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-28T17:24:51.469182+00:00, execution_date=20240628T172451, start_date=20240628T172501, end_date=20240628T172813
[2024-06-28T17:28:13.144+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-28T17:28:13.159+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-28T17:28:13.160+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
