[2024-06-28T22:11:51.693+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:11:51.720+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:11:47.269421+00:00 [queued]>
[2024-06-28T22:11:51.728+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:11:47.269421+00:00 [queued]>
[2024-06-28T22:11:51.729+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T22:11:51.745+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 22:11:47.269421+00:00
[2024-06-28T22:11:51.754+0000] {standard_task_runner.py:63} INFO - Started process 412 to run task
[2024-06-28T22:11:51.757+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T22:11:47.269421+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpxwn_x_zf']
[2024-06-28T22:11:51.760+0000] {standard_task_runner.py:91} INFO - Job 146: Subtask data_delivery
[2024-06-28T22:11:51.809+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:11:47.269421+00:00 [running]> on host 79a59ce16f65
[2024-06-28T22:11:52.066+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T22:11:47.269421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T22:11:47.269421+00:00'
[2024-06-28T22:11:52.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:11:52.076+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T22:11:52.076+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T22:11:52.083+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:11:52.087+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T22:11:52.212+0000] {Load_Data.py:89} INFO - DimLocation dimension loaded successfully
[2024-06-28T22:11:52.213+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:11:52.213+0000] {Load_Data.py:97} INFO - loading DimRate Dimension ...
[2024-06-28T22:11:52.216+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T22:11:52.219+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:11:52.228+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T22:11:52.229+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:11:52.229+0000] {Load_Data.py:100} INFO - DimRate_df dimension loaded successfully
[2024-06-28T22:11:52.229+0000] {Load_Data.py:115} INFO - loading payment dimension....
[2024-06-28T22:11:52.231+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T22:11:52.234+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:11:52.241+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T22:11:52.241+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:11:52.241+0000] {Load_Data.py:118} INFO - payment_df dimension loaded successfully
[2024-06-28T22:11:52.241+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T22:11:52.243+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T22:11:52.246+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:11:52.254+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T22:11:52.254+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:11:52.254+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T22:11:52.254+0000] {Load_Data.py:106} INFO - loading trip_type dimension....
[2024-06-28T22:11:52.256+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T22:11:52.259+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:11:52.264+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T22:11:52.265+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:11:52.265+0000] {Load_Data.py:109} INFO - trip_df dimension loaded successfully
[2024-06-28T22:11:52.265+0000] {Load_Data.py:124} INFO - loading fact table ....
[2024-06-28T22:11:55.794+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T22:11:55.797+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:13:07.450+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T22:13:07.452+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:13:07.453+0000] {process_utils.py:132} INFO - Sending 15 to group 412. PIDs of all processes in the group: [412]
[2024-06-28T22:13:07.453+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 412
[2024-06-28T22:13:07.454+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T22:13:07.461+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:13:07.666+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=412, status='terminated', exitcode=0, started='22:11:51') (412) terminated with exit code 0
