[2024-06-28T22:18:08.628+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-28T22:18:08.653+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:18:04.721493+00:00 [queued]>
[2024-06-28T22:18:08.662+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:18:04.721493+00:00 [queued]>
[2024-06-28T22:18:08.662+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-28T22:18:08.676+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-28 22:18:04.721493+00:00
[2024-06-28T22:18:08.684+0000] {standard_task_runner.py:63} INFO - Started process 430 to run task
[2024-06-28T22:18:08.687+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-28T22:18:04.721493+00:00', '--job-id', '152', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpzarl5sd8']
[2024-06-28T22:18:08.689+0000] {standard_task_runner.py:91} INFO - Job 152: Subtask data_delivery
[2024-06-28T22:18:08.734+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-28T22:18:04.721493+00:00 [running]> on host 79a59ce16f65
[2024-06-28T22:18:09.053+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-28T22:18:04.721493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-28T22:18:04.721493+00:00'
[2024-06-28T22:18:09.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-28T22:18:09.065+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-28T22:18:09.066+0000] {Load_Data.py:20} INFO - Loading location Dimension ...
[2024-06-28T22:18:09.073+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:18:09.076+0000] {Load_Data.py:36} INFO - Existing records columns: ['locationid', 'borough', 'zone', 'service_zone', 'start_date', 'end_date', 'active_flag', 'version']
[2024-06-28T22:18:09.216+0000] {Load_Data.py:89} INFO - DimLocation dimension loaded successfully
[2024-06-28T22:18:09.216+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:18:09.217+0000] {Load_Data.py:97} INFO - loading DimRate Dimension ...
[2024-06-28T22:18:09.219+0000] {Table_creation.py:30} INFO - Loading data into table DimRate...
[2024-06-28T22:18:09.223+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:18:09.233+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimRate With 6 Row
[2024-06-28T22:18:09.233+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:18:09.233+0000] {Load_Data.py:100} INFO - DimRate_df dimension loaded successfully
[2024-06-28T22:18:09.234+0000] {Load_Data.py:115} INFO - loading payment dimension....
[2024-06-28T22:18:09.236+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-28T22:18:09.239+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:18:09.246+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-28T22:18:09.246+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:18:09.246+0000] {Load_Data.py:118} INFO - payment_df dimension loaded successfully
[2024-06-28T22:18:09.247+0000] {Load_Data.py:11} INFO - loading Dimvendor Dimension ...
[2024-06-28T22:18:09.249+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-28T22:18:09.252+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:18:09.257+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-28T22:18:09.257+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:18:09.258+0000] {Load_Data.py:14} INFO - Dimvedor_df dimension loaded successfully
[2024-06-28T22:18:09.258+0000] {Load_Data.py:106} INFO - loading trip_type dimension....
[2024-06-28T22:18:09.260+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-28T22:18:09.263+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:18:09.268+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-28T22:18:09.268+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-28T22:18:09.268+0000] {Load_Data.py:109} INFO - trip_df dimension loaded successfully
[2024-06-28T22:18:09.268+0000] {Load_Data.py:124} INFO - loading fact table ....
[2024-06-28T22:18:13.007+0000] {Table_creation.py:30} INFO - Loading data into table Fact_Trip...
[2024-06-28T22:18:13.010+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-28T22:20:19.921+0000] {local_task_job_runner.py:310} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-06-28T22:20:19.922+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2024-06-28T22:20:19.924+0000] {process_utils.py:132} INFO - Sending 15 to group 430. PIDs of all processes in the group: [430]
[2024-06-28T22:20:19.924+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 430
[2024-06-28T22:20:19.924+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-06-28T22:20:19.927+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-28T22:20:20.097+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=430, status='terminated', exitcode=0, started='22:18:08') (430) terminated with exit code 0
