[2024-06-14T08:33:13.041+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T08:33:13.063+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:31:31.626625+00:00 [queued]>
[2024-06-14T08:33:13.074+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:31:31.626625+00:00 [queued]>
[2024-06-14T08:33:13.074+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T08:33:13.119+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-14 08:31:31.626625+00:00
[2024-06-14T08:33:13.126+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-06-14T08:33:13.186+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-14T08:31:31.626625+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpz835keuo']
[2024-06-14T08:33:13.189+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask data_delivery
[2024-06-14T08:33:13.262+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:31:31.626625+00:00 [running]> on host 762c91fd0326
[2024-06-14T08:33:13.595+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T08:31:31.626625+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T08:31:31.626625+00:00'
[2024-06-14T08:33:13.596+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T08:33:13.628+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-14T08:33:13.628+0000] {Load_Data.py:19} INFO - loading location Dimension ...
[2024-06-14T08:33:13.633+0000] {Table_creation.py:30} INFO - Loading data into table DimLocation...
[2024-06-14T08:33:13.637+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:33:13.961+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimLocation With 265 Row
[2024-06-14T08:33:13.962+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-14T08:33:13.962+0000] {Load_Data.py:22} INFO - DimLocation_df dimension loaded successfully
[2024-06-14T08:33:13.963+0000] {Load_Data.py:28} INFO - loading DimRate Dimension ...
[2024-06-14T08:33:13.968+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-14T08:33:13.971+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:33:14.092+0000] {Load_Data.py:33} INFO - Error loading DimRate dimension: column "locationid" of relation "dimvendor" does not exist
LINE 1: INSERT INTO DimVendor (LocationID, Borough, Zone, service_zo...
                               ^

[2024-06-14T08:33:14.092+0000] {Load_Data.py:46} INFO - loading payment dimension....
[2024-06-14T08:33:14.094+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-14T08:33:14.097+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:33:14.200+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-14T08:33:14.200+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-14T08:33:14.201+0000] {Load_Data.py:49} INFO - payment_df dimension loaded successfully
[2024-06-14T08:33:14.201+0000] {Load_Data.py:10} INFO - loading vendor Dimension ...
[2024-06-14T08:33:14.203+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-14T08:33:14.206+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:33:14.311+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimVendor With 2 Row
[2024-06-14T08:33:14.311+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-14T08:33:14.312+0000] {Load_Data.py:13} INFO - vendor_df dimension loaded successfully
[2024-06-14T08:33:14.312+0000] {Load_Data.py:37} INFO - loading trip_type dimension....
[2024-06-14T08:33:14.315+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-14T08:33:14.320+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:33:14.422+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimTrip_type With 2 Row
[2024-06-14T08:33:14.422+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-14T08:33:14.423+0000] {Load_Data.py:40} INFO - trip_df dimension loaded successfully
[2024-06-14T08:33:14.423+0000] {NYC_Taxi_pipeline.py:60} INFO - data_delivery done
[2024-06-14T08:33:14.423+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-14T08:33:14.424+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T08:33:14.435+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-14T08:31:31.626625+00:00, execution_date=20240614T083131, start_date=20240614T083313, end_date=20240614T083314
[2024-06-14T08:33:14.505+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-14T08:33:14.521+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T08:33:14.554+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
