[2024-06-14T08:22:05.837+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-14T08:22:05.856+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:20:39.930078+00:00 [queued]>
[2024-06-14T08:22:05.863+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:20:39.930078+00:00 [queued]>
[2024-06-14T08:22:05.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-14T08:22:05.874+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): data_delivery> on 2024-06-14 08:20:39.930078+00:00
[2024-06-14T08:22:05.881+0000] {standard_task_runner.py:63} INFO - Started process 66 to run task
[2024-06-14T08:22:05.884+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'NYC_Taxi_pipeline', 'data_delivery', 'manual__2024-06-14T08:20:39.930078+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/NYC_Taxi_pipeline.py', '--cfg-path', '/tmp/tmpo0r_e7ux']
[2024-06-14T08:22:05.886+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask data_delivery
[2024-06-14T08:22:05.926+0000] {task_command.py:426} INFO - Running <TaskInstance: NYC_Taxi_pipeline.data_delivery manual__2024-06-14T08:20:39.930078+00:00 [running]> on host 762c91fd0326
[2024-06-14T08:22:06.158+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Mahmoud' AIRFLOW_CTX_DAG_ID='NYC_Taxi_pipeline' AIRFLOW_CTX_TASK_ID='data_delivery' AIRFLOW_CTX_EXECUTION_DATE='2024-06-14T08:20:39.930078+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-14T08:20:39.930078+00:00'
[2024-06-14T08:22:06.159+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-14T08:22:06.168+0000] {NYC_Taxi_pipeline.py:54} INFO - data_delivery started
[2024-06-14T08:22:06.168+0000] {Load_Data.py:19} INFO - loading location Dimension ...
[2024-06-14T08:22:06.172+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-14T08:22:06.175+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:22:06.176+0000] {Load_Data.py:24} INFO - Error loading Location dimension: relation "dimvendor" does not exist

[2024-06-14T08:22:06.177+0000] {Load_Data.py:28} INFO - loading DimRate Dimension ...
[2024-06-14T08:22:06.179+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-14T08:22:06.181+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:22:06.182+0000] {Load_Data.py:33} INFO - Error loading DimRate dimension: relation "dimvendor" does not exist

[2024-06-14T08:22:06.182+0000] {Load_Data.py:46} INFO - loading payment dimension....
[2024-06-14T08:22:06.185+0000] {Table_creation.py:30} INFO - Loading data into table DimPayment...
[2024-06-14T08:22:06.187+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:22:06.205+0000] {Table_creation.py:45} INFO - Data loaded successfully into table DimPayment With 6 Row
[2024-06-14T08:22:06.205+0000] {db_utils.py:30} INFO - PostgreSQL connection is closed
[2024-06-14T08:22:06.205+0000] {Load_Data.py:49} INFO - payment_df dimension loaded successfully
[2024-06-14T08:22:06.205+0000] {Load_Data.py:10} INFO - loading vendor Dimension ...
[2024-06-14T08:22:06.207+0000] {Table_creation.py:30} INFO - Loading data into table DimVendor...
[2024-06-14T08:22:06.210+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:22:06.210+0000] {Load_Data.py:15} INFO - Error loading vendor dimension: relation "dimvendor" does not exist

[2024-06-14T08:22:06.211+0000] {Load_Data.py:37} INFO - loading trip_type dimension....
[2024-06-14T08:22:06.212+0000] {Table_creation.py:30} INFO - Loading data into table DimTrip_type...
[2024-06-14T08:22:06.215+0000] {db_utils.py:21} INFO - Connected to PostgreSQL database successfully
[2024-06-14T08:22:06.216+0000] {Load_Data.py:42} INFO - Error loading trip dimension: relation "dimtrip_type" does not exist

[2024-06-14T08:22:06.216+0000] {NYC_Taxi_pipeline.py:60} INFO - data_delivery done
[2024-06-14T08:22:06.216+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-14T08:22:06.217+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-14T08:22:06.224+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=NYC_Taxi_pipeline, task_id=data_delivery, run_id=manual__2024-06-14T08:20:39.930078+00:00, execution_date=20240614T082039, start_date=20240614T082205, end_date=20240614T082206
[2024-06-14T08:22:06.256+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-14T08:22:06.277+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-14T08:22:06.279+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
